# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- dev

pool:
  vmImage: 'macos-latest'

steps:

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'key.jks'


- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'key.jks'
    apksignerKeystorePassword: 'Adonese=1994'
    apksignerKeystoreAlias: 'key0'
    apksignerKeyPassword: 'Adonese=1994'



- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    options: "--stacktrace"
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

